# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# Python Path
export PYTHONPATH=~/usr/local/bin
# Node
export NPM_PACKAGES="$HOME/.npm"
export PATH="$NPM_PACKAGES/bin:${PATH}"
# Default Editor
export EDITOR=vim
# VSCode
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# Needed for some Python modules
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# Brew needs this Path
export PATH="/usr/local/sbin:$PATH"
# Colors correct in tmux
export TERM=screen-256color
# VI mode in the terminal. ESC for visual, i for insert mode.
set -o vi

# Name of the theme to load.

ZSH_THEME="alex"

# Plugins to load
plugins=(
  git
  macos
  z
  fzf
)

# Personal aliases
# Editing this file
alias zc="vim ~/.zshrc"
alias so="source ~/.zshrc "
# Remove Directories
alias rf="rm -rf"	
# Colorls Aliases
alias lc='colorls -lA --sd --gs'
alias ls='colorls'
alias git='LANG=en_US git'
# Use Brew Vim instead of System Vim
alias vi='/opt/homebrew/bin/vim'
alias vim='/opt/homebrew/bin/vim'
# Always Python3
alias python="python3"

# Test Shell integration for iterm2
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Get output from gitignore.io.
function gi() {
   local IFS=","
   local list="$*"
   if [[ ! "$list" =~ ^[a-zA-Z0-9_\+,\-]+$ ]] && [[ -n "$list" ]]; then
     echo "Error: Invalid characters in gitignore list."
     return 1
   fi
   curl -L -s "https://www.gitignore.io/api/$list"
}
# Make gitignore.io work with FZF.
function gifzf() {
   local list=$(gi list | tr , '\n' | fzf --multi | tr '\n' , | sed 's/,$//' )
   gi $list
}

function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d "$1" ]; then
    echo "\`$1' already exists"
  else
    mkdir -- "$1" && cd -- "$1"
  fi
}

source $ZSH/oh-my-zsh.sh


export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# FZF: a fuzzy Finder, Finder history etc.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh 


# shift tab in ls/cs/...
bindkey '^[[Z' reverse-menu-complete
export PATH="/usr/local/opt/node@14/bin:$PATH"

# fixes the up and down arrow based search so that it does not bug out after
# first blank
export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
