# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# Python Path
export PYTHONPATH=~/usr/local/bin
# Node
export NPM_PACKAGES="$HOME/.npm"
export PATH="$NPM_PACKAGES/bin:${PATH}"
# Fastlane
export PATH="$HOME/.fastlane/bin:$PATH"
# Default Editor
export EDITOR=vim
# VSCode
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# Needed for some Python modules
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# Brew needs this Path
export PATH="/usr/local/sbin:$PATH"
# For Fastlane to be able to update without sudo: https://docs.fastlane.tools/actions/update_fastlane/
export GEM_HOME=~/.gems
export PATH=$PATH:~/.gems/bin
# Colors correct in tmux
export TERM=screen-256color
# VI mode in the terminal. ESC for visual, i for insert mode.
set -o vi

# Name of the theme to load.
ZSH_THEME="alex"

# Plugins to load
plugins=(
  git
  osx
  z
  git-flow
  fzf
)

# Personal aliases
# Editing this file
alias zc="vim ~/.zshrc"
alias so="source ~/.zshrc "
# Remove Directories
alias rf="rm -rf"	
# Colorls Aliases
alias lc='colorls -lA --sd --gs'
alias ls='colorls'
alias git='LANG=en_US git'
# Use Brew Vim instead of System Vim
alias vi='/usr/local/bin/vim'
alias vim='/usr/local/bin/vim'

# Test Shell integration for iterm2
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Get output from gitignore.io.
function gi() {
   curl -L -s https://www.gitignore.io/api/$@

}
# Make gitignore.io work with FZF.
function gifzf() {
   local list=$(gi list | tr , '\n' | fzf --multi | tr '\n' , | sed 's/,$//' )
   gi $list
}

function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d $1 ]; then
    echo "\`$1' already exists"
  else
    mkdir $1 && cd $1
  fi
}

source $ZSH/oh-my-zsh.sh
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# FZF: a fuzzy Finder, Finder history etc.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh 


# added by travis gem
[ -f /Users/alex/.travis/travis.sh ] && source /Users/alex/.travis/travis.sh
